// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5RBjmBQv3iBcvcWTRzNnHaFUlkT3YLg',
    appId: '1:337197672222:web:ccbc26c318e13b0a380b0f',
    messagingSenderId: '337197672222',
    projectId: 'deeptalkchat',
    authDomain: 'deeptalkchat.firebaseapp.com',
    storageBucket: 'deeptalkchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5H9oqukuh8PaUMgq8aamYeUwJAexMtw',
    appId: '1:337197672222:android:da8a733202a5a543380b0f',
    messagingSenderId: '337197672222',
    projectId: 'deeptalkchat',
    storageBucket: 'deeptalkchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_QdTJQTa_YGntMzXqn1Kc1fLtlDAMZk',
    appId: '1:337197672222:ios:4a00df8b01c8d316380b0f',
    messagingSenderId: '337197672222',
    projectId: 'deeptalkchat',
    storageBucket: 'deeptalkchat.appspot.com',
    iosClientId: '337197672222-tmd69sjrq5mlbj431pqfppj8shdlti9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.dechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_QdTJQTa_YGntMzXqn1Kc1fLtlDAMZk',
    appId: '1:337197672222:ios:4a00df8b01c8d316380b0f',
    messagingSenderId: '337197672222',
    projectId: 'deeptalkchat',
    storageBucket: 'deeptalkchat.appspot.com',
    iosClientId: '337197672222-tmd69sjrq5mlbj431pqfppj8shdlti9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.dechat',
  );
}
